name: Terraform CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:

  scan:
    name: Terraform Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: prod/environment

      - name: Terraform Validate
        run: terraform validate
        working-directory: prod/environment