name: Terraform CI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  scan:
    name: Terraform Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Repository Structure
        run: |
          pwd
          ls -la
          ls -la prod
          ls -la prod/environment

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init --backend=false
        working-directory: prod/environment

      - name: Terraform Validate
        run: terraform validate
        working-directory: prod/environment

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Initialize TFLint
        run: tflint --init
        working-directory: prod/environment
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact
        working-directory: prod/environment
